name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql, dom, curl, libxml, zip, pcntl, soap, intl, gd, exif, iconv

      # 6. Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # 7. Build frontend assets
      - name: Build assets
        run: npm run build

      # 3. Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev

      # 5. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 10. Deploy to FTP server using SFTP over port 22
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ssh.strato.com
          username: 570388511.swh.strato-hosting.eu
          password: Windiesoft#1964
          local-dir: ./  # This should include all files in your project
          server-dir: /flexty/public/
          exclude: |
            .git*
            node_modules/**
            storage/debugbar/**
            tests/**
            vendor/**
            *.md
          port: 22  # Add port 22 for SFTP connection
          timeout: 120
